source("loaddata.R")

consumption_data <- load_data()

attach(consumption_data)
png("plot4.png", width=480, height=480, units="px")
par(mfrow=c(2,2))
plot(Time, Global_active_power, type="l", xlab="", ylab="Global Active Power")
plot(Time,Voltage, type="l", xlab="datetime", ylab="Voltage")
plot(Time, Sub_metering_1, type="l", xlab="", ylab="Energy sub metering")
lines(Time, as.numeric(as.character(Sub_metering_2)), col="red")
lines(Time, as.numeric(as.character(Sub_metering_3)), col="blue")
legend("topright", lty=1, bty="n", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3" ))
plot(Time, Global_reactive_power, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()
